name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${12.x}
        uses: actions/setup-node@v1
        with:
          node-version: ${12.x}
      - run: echo 'Hello world'
      - run: npm ci
      - run: npm run test
        env:
          CI: true
